openapi: 3.0.0
info:
  title: nest
  description: Nest is a students app.
  contact:
    name: Atuhaire Collins
    email: collinsbenda360@gmail.com
  version: "1.0"
servers:
  - url: http://localhost:5000/api/v1
    variables: {}
